// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UijobsApi.Data;

#nullable disable

namespace UijobsApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230714013917_InicialCreate")]
    partial class InicialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UijobsApi.Models.Candidato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeMae")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Candidatos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cep = "02124050",
                            Email = "yago.pereira7@etec.sp.gov.br",
                            Nome = "Yago",
                            NomeMae = "Elaine"
                        },
                        new
                        {
                            Id = 2,
                            Cep = "02124040",
                            Email = "Daniel@etec.sp.gov.br",
                            Nome = "Daniel",
                            NomeMae = "Maria"
                        },
                        new
                        {
                            Id = 3,
                            Cep = "02179010",
                            Email = "Lara@etec.sp.gov.br",
                            Nome = "Lara",
                            NomeMae = "Maria Beatriz"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
